name: "Execução agendado"

#gatilho de execução manual = workflow_dispatch
on:
  schedule: 
    - cron: "0 0 1 1,7 *" # Executa à meia-noite no dia 1 de janeiro e 1 de julho

jobs:
  e2e-tests:
    runs-on: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando testes de acessibilidade 
        run: npm i cypress-axe cypress-axe-core

      - name: Instalando o relatório de testes
        run: npm i mochawesome cypress-mochawesome-reporter --save-dev

      - name: Testes E2E
        run: npx cypress run
